# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 2,12 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: waynerv
          template: classic
          base: activity, community, repositories
          config_timezone: Asia/Shanghai
          plugin_lines: yes
          plugin_rss: yes
          plugin_rss_limit: 3
          plugin_rss_source: https://www.waynerv.com/rss.xml
